// Generated by CIRCT firtool-1.75.0
module ResetWrangler(	// @[generators/rocket-chip/src/main/scala/prci/ResetWrangler.scala:16:9]
  input  auto_in_3_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  auto_in_3_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  auto_in_2_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  auto_in_2_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  auto_in_1_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  auto_in_1_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  auto_in_0_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  auto_in_0_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output auto_out_3_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output auto_out_2_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output auto_out_1_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output auto_out_0_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output auto_out_0_reset	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  wire        _deglitched_deglitch_io_q;	// @[generators/rocket-chip/src/main/scala/util/AsyncResetReg.scala:71:21]
  wire [12:0] _debounced_debounce_io_q;	// @[generators/rocket-chip/src/main/scala/util/AsyncResetReg.scala:86:21]
  wire        causes = auto_in_0_reset | auto_in_1_reset | auto_in_2_reset | auto_in_3_reset;	// @[generators/rocket-chip/src/main/scala/prci/ResetWrangler.scala:22:61]
  wire        increment = _debounced_debounce_io_q != 13'h1388;	// @[generators/rocket-chip/src/main/scala/prci/ResetWrangler.scala:36:28, generators/rocket-chip/src/main/scala/util/AsyncResetReg.scala:86:21]
  AsyncResetRegVec_w13_i0 debounced_debounce (	// @[generators/rocket-chip/src/main/scala/util/AsyncResetReg.scala:86:21]
    .clock (auto_in_0_clock),
    .reset (causes),	// @[generators/rocket-chip/src/main/scala/prci/ResetWrangler.scala:22:61]
    .io_d  (_debounced_debounce_io_q + 13'h1),	// @[generators/rocket-chip/src/main/scala/prci/ResetWrangler.scala:37:30, generators/rocket-chip/src/main/scala/util/AsyncResetReg.scala:86:21]
    .io_q  (_debounced_debounce_io_q),
    .io_en (increment)	// @[generators/rocket-chip/src/main/scala/prci/ResetWrangler.scala:36:28]
  );	// @[generators/rocket-chip/src/main/scala/util/AsyncResetReg.scala:86:21]
  AsyncResetReg deglitched_deglitch (	// @[generators/rocket-chip/src/main/scala/util/AsyncResetReg.scala:71:21]
    .io_d   (increment),	// @[generators/rocket-chip/src/main/scala/prci/ResetWrangler.scala:36:28]
    .io_q   (_deglitched_deglitch_io_q),
    .io_clk (auto_in_0_clock),
    .io_rst (causes)	// @[generators/rocket-chip/src/main/scala/prci/ResetWrangler.scala:22:61]
  );	// @[generators/rocket-chip/src/main/scala/util/AsyncResetReg.scala:71:21]
  ResetCatchAndSync_d3 nodeOut_reset_catcher (	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (auto_in_0_clock),
    .reset         (_deglitched_deglitch_io_q),	// @[generators/rocket-chip/src/main/scala/util/AsyncResetReg.scala:71:21]
    .io_sync_reset (auto_out_0_reset)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  ResetCatchAndSync_d3 nodeOut_reset_catcher_1 (	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (auto_in_1_clock),
    .reset         (_deglitched_deglitch_io_q),	// @[generators/rocket-chip/src/main/scala/util/AsyncResetReg.scala:71:21]
    .io_sync_reset (/* unused */)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  ResetCatchAndSync_d3 nodeOut_reset_catcher_2 (	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (auto_in_2_clock),
    .reset         (_deglitched_deglitch_io_q),	// @[generators/rocket-chip/src/main/scala/util/AsyncResetReg.scala:71:21]
    .io_sync_reset (/* unused */)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  ResetCatchAndSync_d3 nodeOut_reset_catcher_3 (	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (auto_in_3_clock),
    .reset         (_deglitched_deglitch_io_q),	// @[generators/rocket-chip/src/main/scala/util/AsyncResetReg.scala:71:21]
    .io_sync_reset (auto_out_3_reset)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  assign auto_out_2_clock = auto_in_2_clock;	// @[generators/rocket-chip/src/main/scala/prci/ResetWrangler.scala:16:9]
  assign auto_out_1_clock = auto_in_1_clock;	// @[generators/rocket-chip/src/main/scala/prci/ResetWrangler.scala:16:9]
  assign auto_out_0_clock = auto_in_0_clock;	// @[generators/rocket-chip/src/main/scala/prci/ResetWrangler.scala:16:9]
endmodule

