name: Build Verilog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      # with:
      #   submodules: recursive

    - name: Run make verilog
      run: |
        make verilog
