name: Build Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      # with:
      #   submodules: recursive

    - name: Set up Toolchain
      run: source $GITHUB_WORKSPACE/scripts/install-mill.sh

    - name: Run make verilog
      run: |
        export PATH=$GITHUB_WORKSPACE/toolchains:$PATH
        make verilog
