name: Run Vivado Flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Vivado
      run: source /ecad/tools/xilinx/Vivado/2023.2.1/settings64.sh

    - name: Run Vivado Flow
      run: |
        source ./env.sh
        make project CONFIG=MlpPolicyRunner
